described_by_source('islam', 'islamskiy_enciklopedicheskiy_slovar').
described_by_source('islam', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('islam', 'catholic_encyclopedia').
described_by_source('islam', 'the_nuttall_encyclop_dia').
described_by_source('islam', 'new_encyclopedic_dictionary').
described_by_source('islam', 'ott_v_slovn_k_nau_n_').
described_by_source('islam', 'jewish_encyclopedia_of_brockhaus_and_efron').
described_by_source('islam', 'encyclop_dia_britannica_11th_edition').
described_by_source('islam', 'new_international_encyclopedia__1902_1905_').
described_by_source('islam', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('buddhism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('buddhism', 'metropolitan_museum_of_art_tagging_vocabulary').
described_by_source('buddhism', 'gujin_tushu_jicheng').
described_by_source('hinduism', 'the_nuttall_encyclop_dia').
described_by_source('hinduism', 'ott_v_slovn_k_nau_n_').
described_by_source('hinduism', 'hindu_astrology').
described_by_source('hinduism', 'great_soviet_encyclopedia__1926_1947_').
described_by_source('hinduism', 'metropolitan_museum_of_art_tagging_vocabulary').
described_by_source('hinduism', 'new_encyclopedic_dictionary').
described_by_source('hinduism', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('hinduism', 'vedas').
described_by_source('taoism', 'the_nuttall_encyclop_dia').
described_by_source('taoism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('taoism', 'metropolitan_museum_of_art_tagging_vocabulary').
described_by_source('taoism', 'gujin_tushu_jicheng').
described_by_source('taoism', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('confucianism', 'records_of_the_grand_historian').
described_by_source('confucianism', 'encyclopedia_of_political_theory__2010_ed__').
described_by_source('confucianism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('confucianism', 'catholic_encyclopedia').
described_by_source('animism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('animism', 'the_nuttall_encyclop_dia').
described_by_source('shamanism', 'great_soviet_encyclopedia__1926_1947_').
described_by_source('shamanism', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('shamanism', 'the_nuttall_encyclop_dia').
described_by_source('catharism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('catharism', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('catharism', 'the_nuttall_encyclop_dia').
described_by_source('catharism', 'ott_v_slovn_k_nau_n_').
described_by_source('catharism', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('catharism', 'encyclop_dia_britannica_11th_edition').
described_by_source('catharism', 'new_international_encyclopedia').
described_by_source('religion_of_ancient_egypt', 'armenian_soviet_encyclopedia__vol__3').
described_by_source('unitarianism', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('unitarianism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('unitarianism', 'the_nuttall_encyclop_dia').
described_by_source('unitarianism', 'encyclop_dia_britannica_11th_edition').
described_by_source('ancient_roman_religion', 'real_nyj_slovar__klassicheskih_drevnostej_po_ljubkeru').
described_by_source('ancient_roman_religion', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('ancient_roman_religion', 'encyclop_dia_britannica_11th_edition').
described_by_source('b_bism', 'great_soviet_encyclopedia__1926_1947_').
described_by_source('b_bism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('b_bism', 'the_nuttall_encyclop_dia').
described_by_source('b_bism', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('b_bism', 'ott_v_slovn_k_nau_n_').
described_by_source('b_bism', 'islamskiy_enciklopedicheskiy_slovar').
described_by_source('b_bism', 'encyclop_dia_britannica_11th_edition').
described_by_source('b_bism', 'encyclop_dia_britannica_ninth_edition').
described_by_source('b_bism', 'new_international_encyclopedia').
described_by_source('historical_vedic_religion', 'the_nuttall_encyclop_dia').
described_by_source('historical_vedic_religion', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('historical_vedic_religion', 'encyclop_dia_britannica_11th_edition').
described_by_source('historical_vedic_religion', 'granat_encyclopedic_dictionary').
described_by_source('sumerian_religion', 'orthodox_theological_encyclopedia').
described_by_source('arminianism', 'the_nuttall_encyclop_dia').
described_by_source('arminianism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('arminianism', 'great_soviet_encyclopedia__1926_1947_').
described_by_source('arminianism', 'orthodox_theological_encyclopedia').
described_by_source('arminianism', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('arminianism', 'catholic_encyclopedia').
described_by_source('arminianism', 'granat_encyclopedic_dictionary').
described_by_source('gallicanism', 'the_nuttall_encyclop_dia').
described_by_source('gallicanism', 'encyclop_dia_britannica_11th_edition').
described_by_source('gallicanism', 'catholic_encyclopedia').
described_by_source('hanif', 'encyclopaedia_of_the_qur__n').
described_by_source('hanif', 'the_nuttall_encyclop_dia').
described_by_source('brahmanism', 'orthodox_theological_encyclopedia').
described_by_source('brahmanism', 'new_encyclopedic_dictionary').
described_by_source('brahmanism', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('brahmanism', 'great_soviet_encyclopedia__1926_1947_').
described_by_source('brahmanism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('pastafarianism', 'the_gospel_of_the_flying_spaghetti_monster').
described_by_source('pastafarianism', 'open_letter_to_kansas_school_board').
described_by_source('canaanite_religion', 'infogalactic').
described_by_source('canaanite_religion', 'encyclopedia_com').
described_by_source('canaanite_religion', 'everipedia').
described_by_source('anglo_catholicism', 'the_palgrave_encyclopedia_of_victorian_women_s_writing').
described_by_source('ancient_mesopotamian_religion', 'encyclop_dia_britannica_11th_edition').
described_by_source('low_church', 'the_nuttall_encyclop_dia').
described_by_source('low_church', 'encyclop_dia_britannica_11th_edition').
described_by_source('theology_of_huldrych_zwingli', 'dictionnaire_de_th_ologie_catholique').
described_by_source('hypsistarians', 'jewish_encyclopedia_of_brockhaus_and_efron').
described_by_source('mazdaism', 'great_soviet_encyclopedia__1926_1947_').
described_by_source('primitive_baptists', 'the_encyclopedia_americana').
described_by_source('anupa', 'political_history_of_ancient_india__from_the_accession_of_parikshit_to_the_extinction_of_the_gupta_dynasty').
described_by_source('wesenmystik', 'hts_theological_studies').
described_by_source('franciscan_spirituality', 'encyclopedia_com').
described_by_source('philistine_religion', 'old_testament').
described_by_source('monism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('monism', 'new_encyclopedic_dictionary').
described_by_source('monism', 'the_nuttall_encyclop_dia').
described_by_source('monism', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('monism', 'great_soviet_encyclopedia__1926_1947_').
described_by_source('monism', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('platonism', 'armenian_soviet_encyclopedia__vol__9').
described_by_source('fatalism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('fatalism', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('nominalism', 'new_encyclopedic_dictionary').
described_by_source('nominalism', 'the_nuttall_encyclop_dia').
described_by_source('nominalism', 'encyclop_dia_britannica_11th_edition').
described_by_source('nominalism', 'new_international_encyclopedia').
described_by_source('sensationism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('sensationism', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('sensationism', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('sensationism', 'armenian_soviet_encyclopedia__vol__10').
described_by_source('obscurantism', 'the_nuttall_encyclop_dia').
described_by_source('obscurantism', 'meyers_konversations_lexikon__4th_edition__1885_1890_').
described_by_source('obscurantism', 'encyclopedic_dictionary_of__ism_s').
described_by_source('obscurantism', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('obscurantism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('pluralism', 'ott_v_slovn_k_nau_n_').
described_by_source('pluralism', 'encyclop_dia_britannica_11th_edition').
described_by_source('hylozoism', 'ott_v_slovn_k_nau_n_').
described_by_source('hylozoism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('hylozoism', 'great_soviet_encyclopedia__1926_1947_').
described_by_source('hylozoism', 'encyclop_dia_britannica_11th_edition').
described_by_source('hylozoism', 'granat_encyclopedic_dictionary').
described_by_source('conceptualism', 'armenian_soviet_encyclopedia').
described_by_source('conceptualism', 'encyclop_dia_britannica_11th_edition').
described_by_source('euhemerism', 'the_nuttall_encyclop_dia').
described_by_source('acosmism', 'granat_encyclopedic_dictionary').
described_by_source('acosmism', 'ott_v_slovn_k_nau_n_').
described_by_source('acosmism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('acosmism', 'great_soviet_encyclopedia__1926_1947_').
described_by_source('innatism', 'small_brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('innatism', 'treccani_philosophy').
described_by_source('innatism', 'brockhaus_and_efron_encyclopedic_dictionary').
described_by_source('transcendental_idealism', 'the_american_cyclop_dia').
described_by_source('logical_atomism', 'armenian_soviet_encyclopedia').
described_by_source('conventionalism', 'armenian_soviet_encyclopedia__vol__5').
described_by_source('spiritualism', 'granat_encyclopedic_dictionary').
described_by_source('contractualism', 'encyclopedia_of_political_theory__2010_ed__').
described_by_source('parallelism', 'encyclop_dia_britannica_11th_edition').
described_by_source('parallelism', 'armenian_soviet_encyclopedia__vol__6').
described_by_source('double_truth', 'armenian_soviet_encyclopedia__vol__3').
described_by_source('meliorism', 'the_nuttall_encyclop_dia').
described_by_source('actualism', 'armenian_soviet_encyclopedia__vol__1').
described_by_source('best_of_all_possible_worlds', 'the_nuttall_encyclop_dia').
described_by_source('corpuscularianism', 'the_nuttall_encyclop_dia').
described_by_source('emergentism', 'the_nuttall_encyclop_dia').
described_by_source('labor_theory_of_property_acquisition', 'locke_s_labor_theory_of_original_appropriation__philosophical_significance_and_implications').
described_by_source('labor_theory_of_property_acquisition', 'the_labor_theory_of_property_acquisition').
described_by_source('animalism', 'armenian_soviet_encyclopedia__vol__1').
described_by_source('erastianism', 'the_nuttall_encyclop_dia').
described_by_source('erastianism', 'catholic_encyclopedia').
described_by_source('transcendental_analytic', 'critique_of_pure_reason').
described_by_source('afterlife', 'jewish_encyclopedia_of_brockhaus_and_efron').
described_by_source('astrolatry', 'great_soviet_encyclopedia__1926_1947_').
described_by_source('astrolatry', 'jewish_encyclopedia_of_brockhaus_and_efron').
topic_s_main_category('islam', 'category_islam').
topic_s_main_category('hinduism', 'category_hinduism').
topic_s_main_category('taoism', 'category_taoism').
topic_s_main_category('confucianism', 'category_confucianism').
topic_s_main_category('jainism', 'category_jainism').
topic_s_main_category('bah____faith', 'category_bah____faith').
topic_s_main_category('animism', 'category_animism').
topic_s_main_category('shamanism', 'category_shamanism').
topic_s_main_category('rastafari', 'category_rastafari').
topic_s_main_category('scientology', 'category_scientology').
topic_s_main_category('catharism', 'q7328282').
topic_s_main_category('catharism', 'category_catharism').
topic_s_main_category('religion_of_ancient_egypt', 'category_ancient_egyptian_religion').
topic_s_main_category('modern_paganism', 'category_modern_paganism').
topic_s_main_category('tengrism', 'category_tengriism').
topic_s_main_category('unitarianism', 'category_unitarianism').
topic_s_main_category('ancient_roman_religion', 'category_ancient_roman_religion').
topic_s_main_category('b_bism', 'category_b_bism').
topic_s_main_category('historical_vedic_religion', 'category_vedic_religion').
topic_s_main_category('chinese_folk_religion', 'category_chinese_folk_religion').
topic_s_main_category('thelema', 'category_thelema').
topic_s_main_category('yarsanism', 'category_yarsanism').
topic_s_main_category('sumerian_religion', 'category_sumerian_mythology').
topic_s_main_category('arminianism', 'category_arminianism').
topic_s_main_category('rule_of_osha', 'category_candombl_').
topic_s_main_category('gallicanism', 'category_gallicanism').
topic_s_main_category('yazidism', 'category_yazidism').
topic_s_main_category('discordianism', 'category_discordianism').
topic_s_main_category('germanic_paganism', 'category_germanic_paganism').
topic_s_main_category('modern_asatru', 'category__satr_').
topic_s_main_category('zurvanism', 'q32696175').
topic_s_main_category('proto_indo_european_mythology', 'category_proto_indo_european_mythology').
topic_s_main_category('atenism', 'category_atenism').
topic_s_main_category('heathenry', 'category_germanic_neopaganism').
topic_s_main_category('pastafarianism', 'category_flying_spaghetti_monster').
topic_s_main_category('yoruba_religion', 'category_yoruba_religion').
topic_s_main_category('canaanite_religion', 'category_canaanite_religion').
topic_s_main_category('anglo_catholicism', 'category_anglo_catholicism').
topic_s_main_category('kemetism', 'category_kemetism').
topic_s_main_category('babylonian_religion', 'category_babylonian_religion').
topic_s_main_category('umbanda', 'category_umbanda').
topic_s_main_category('hellenistic_judaism', 'category_hellenistic_judaism').
topic_s_main_category('ancient_mesopotamian_religion', 'category_mesopotamian_religion').
topic_s_main_category('australian_aboriginal_mythology', 'category_australian_aboriginal_mythology').
topic_s_main_category('eckankar', 'category_eck_masters').
topic_s_main_category('native_american_church', 'category_native_american_church').
topic_s_main_category('ariosophy', 'category_ariosophy___armanism').
topic_s_main_category('samaritanism', 'q10175804').
topic_s_main_category('kadam', 'category_kadam__tibetan_buddhism_').
topic_s_main_category('if_', 'category_if__divination').
topic_s_main_category('sallekhana', 'category_sallekhana').
topic_s_main_category('nichiren_sh_sh_', 'category_nichiren_shoshu').
topic_s_main_category('grapevine_cross', 'christian_cross').
topic_s_main_category('second_temple_judaism', 'category_second_temple_judaism').
topic_s_main_category('jewish_renewal', 'category_jewish_renewal').
topic_s_main_category('haitian_vodou', 'category_haitian_vodou').
topic_s_main_category('traditional_berber_religion', 'category_berber_mythology').
topic_s_main_category('polytheistic_reconstructionism', 'category_polytheistic_reconstructionism').
topic_s_main_category('aztec_religion', 'category_aztec_religion').
topic_s_main_category('mari_religion', 'category_mari_native_religion').
topic_s_main_category('sanamahism', 'category_sanamahism').
topic_s_main_category('winti', 'category_winti_in_suriname').
topic_s_main_category('ryukyuan_religion', 'q10806364').
topic_s_main_category('modekngei', 'q9055512').
topic_s_main_category('native_american_religions', 'category_indigenous_religion_of_the_americas').
topic_s_main_category('surat_shabd_yoga', 'category_surat_shabd_yoga').
topic_s_main_category('louisiana_voodoo', 'category_louisiana_voodoo').
topic_s_main_category('brahmoism', 'category_brahmoism').
topic_s_main_category('etruscan_religion', 'category_etruscan_religion').
topic_s_main_category('proto_indo_iranian_religion', 'category_indo_iranian_religion').
topic_s_main_category('nauruan_indigenous_religion', 'category_nauruan_mythology').
topic_s_main_category('donyi_polo', 'category_donyi_polo').
topic_s_main_category('arab_muslims', 'category_arab_muslims').
topic_s_main_category('haymanot', 'category_haymanot').
topic_s_main_category('hetanism', 'category_hetanism').
topic_s_main_category('gallo_roman_religion', 'category_gallo_roman_religion').
topic_s_main_category('yuzu_nembutsu', 'category_y_z__nembutsu_buddhism').
topic_s_main_category('elamite_religion', 'q20184510').
topic_s_main_category('hittite_religion', 'category_hittite_religion').
topic_s_main_category('nabataean_religion', 'nabataeans').
topic_s_main_category('jeung_san_do', 'category_jeung_san_do').
topic_s_main_category('mapuche_religion', 'category_mapuche_religion').
topic_s_main_category('mesoamerican_religion', 'category_mesoamerican_religion').
topic_s_main_category('gonabadi_dervish', 'q32509925').
topic_s_main_category('universalist_church_of_america', 'category_universalist_church_of_america').
topic_s_main_category('__o_m_u', 'category___o_m_u').
topic_s_main_category('ignatian_spirituality', 'category_ignatian_spirituality').
topic_s_main_category('ugaritic_religion', 'q9148736').
topic_s_main_category('international_peace_mission_movement', 'category_international_peace_mission_movement').
topic_s_main_category('amazighs_christians_donatians', 'category_berber_christians').
topic_s_main_category('the_new_church', 'category_the_new_church__swedenborgian_').
topic_s_main_category('dogon_religion', 'category_dogon_religion').
topic_s_main_category('native_american_religion_in_north_america', 'category_native_american_religion').
topic_s_main_category('native_american_religion_in_north_america', 'category_deities_of_the_indigenous_peoples_of_north_america').
topic_s_main_category('monism', 'category_monism').
topic_s_main_category('platonism', 'category_platonism').
topic_s_main_category('physicalism', 'category_physicalism').
topic_s_main_category('pluralism', 'category_pluralism__philosophy_').
topic_s_main_category('conceptualism', 'category_conceptualism').
topic_s_main_category('critical_rationalism', 'q8989848').
topic_s_main_category('ecosophy', 'q9624404').
topic_s_main_category('foundationalism', 'category_foundationalism').
topic_s_main_category('coherentism', 'category_coherentism').
topic_s_main_category('spiritualism', 'category_spiritualism').
topic_s_main_category('social_ecology', 'category_social_ecology').
topic_s_main_category('formalism', 'category_formalism__deductive_').
topic_s_main_category('contractualism', 'category_contractualism').
topic_s_main_category('exceptionalism', 'category_exceptionalism').
topic_s_main_category('postanalytic_philosophy', 'q19637001').
topic_s_main_category('structuralism', 'category_structuralism__philosophy_of_mathematics_').
topic_s_main_category('afterlife', 'category_afterlife').
topic_s_main_category('astrolatry', 'q31998885').
topic_s_main_category('gion_faith', 'category_gion_cult').
topic_s_main_category('sann_', 'category_sann__ichijitsu_shint_').
topic_s_main_category('gory__faith', 'category_gory__faith').
topic_s_main_template('islam', 'template_islam').
topic_s_main_template('islam', 'template_islam_topics').
topic_s_main_template('buddhism', 'template_buddhism_topics').
topic_s_main_template('buddhism', 'template_buddhism').
topic_s_main_template('hinduism', 'template_hinduism').
topic_s_main_template('judaism', 'template_judaism').
topic_s_main_template('taoism', 'template_taoism').
topic_s_main_template('taoism', 'template_taoism_footer').
topic_s_main_template('confucianism', 'template_confucianism').
topic_s_main_template('scientology', 'template_scientology').
topic_s_main_template('modern_paganism', 'template_paganism_topics').
topic_s_main_template('ancient_roman_religion', 'template_roman_religion').
topic_s_main_template('soka_gakkai', 'q18987599').
topic_s_main_template('laveyan_satanism', 'template_laveyan_satanism_sidebar').
topic_s_main_template('laveyan_satanism', 'template_laveyan_satanism').
topic_s_main_template('kemetism', 'template_kemetic').
topic_s_main_template('exceptionalism', 'template_exceptionalism').
topic_s_main_template('afterlife', 'q95622972').
history_of_topic('islam', 'history_of_islam').
history_of_topic('buddhism', 'timeline_of_buddhism').
history_of_topic('buddhism', 'history_of_buddhism').
history_of_topic('hinduism', 'history_of_hinduism').
history_of_topic('judaism', 'jewish_history').
studied_in('islam', 'islamic_studies').
studied_in('confucianism', 'jian_jia_xue_pai').
studied_in('sensationism', 'epistemology').
studied_in('sensationism', 'cognitive_psychology').
studied_in('physicalism', 'philosophy_of_mind').
studied_in('physicalism', 'monism').
has_characteristic('islam', 'monotheism').
has_characteristic('buddhism', 'religious_philosophy').
has_characteristic('hinduism', 'polytheism').
has_characteristic('judaism', 'monotheism').
has_characteristic('zoroastrianism', 'dualistic_cosmology').
has_characteristic('jainism', 'meditation').
has_characteristic('jainism', 'ahimsa').
has_characteristic('tengrism', 'polytheism').
has_characteristic('tengrism', 'indigenism').
has_characteristic('tengrism', 'monotheism').
has_characteristic('ancient_roman_religion', 'polytheism').
has_characteristic('atenism', 'monotheism').
has_characteristic('pastafarianism', 'monotheism').
has_characteristic('aztec_religion', 'polytheism').
has_characteristic('aztec_religion', 'human_sacrifice').
has_characteristic('tai_folk_religion', 'polytheism').
has_characteristic('tai_folk_religion', 'pantheism').
has_characteristic('tai_folk_religion', 'animism').
has_characteristic('tai_folk_religion', 'shamanism').
has_characteristic('samnite_religion', 'polytheism').
has_characteristic('lydian_religion', 'polytheism').
has_characteristic('sabine_religion', 'polytheism').
has_characteristic('philistine_religion', 'polytheism').
influenced_by('islam', 'hanif').
influenced_by('hinduism', 'historical_vedic_religion').
influenced_by('hinduism', 'dravidian_folk_religion').
influenced_by('bah____faith', 'islam').
influenced_by('bah____faith', 'b_bism').
influenced_by('bah____faith', 'shaykhism').
influenced_by('rastafari', 'christianity').
influenced_by('rastafari', 'judaism').
influenced_by('historical_vedic_religion', 'proto_indo_iranian_religion').
influenced_by('yarsanism', 'yazd_nism').
influenced_by('nichiren_sh_sh_', 'nichiren').
influenced_by('haitian_vodou', 'west_african_vodun').
influenced_by('hypsistarians', 'hellenistic_religion').
influenced_by('hypsistarians', 'judaism').
influenced_by('louisiana_voodoo', 'west_african_vodun').
influenced_by('louisiana_voodoo', 'catholicism').
influenced_by('feri_tradition', 'huna').
influenced_by('feri_tradition', 'witchcraft_today').
influenced_by('feri_tradition', 'wicca').
influenced_by('feri_tradition', 'voodoo_church').
influenced_by('feri_tradition', 'gardnerian_wicca').
influenced_by('gonabadi_dervish', 'islam').
influenced_by('longhouse_religion', 'quakers').
influenced_by('zenith_applied_philosophy', 'scientology').
influenced_by('zenith_applied_philosophy', 'eastern_religions').
influenced_by('zenith_applied_philosophy', 'john_birch_society').
influenced_by('zenith_applied_philosophy', 'the_law').
influenced_by('psychedelic_venus_church', 'sexual_freedom_league').
influenced_by('new_materialism', 'gilles_deleuze').
influenced_by('new_materialism', 'f_lix_guattari').
influenced_by('new_materialism', 'benedictus_de_spinoza').
influenced_by('receptivity', 'martin_heidegger').
influenced_by('receptivity', 'stanley_cavell').
influenced_by('receptivity', 'ralph_waldo_emerson').
replaces('islam', 'ancient_semitic_religion').
replaces('islam', 'arabian_mythology').
location_of_formation('islam', 'hejaz').
location_of_formation('hinduism', 'sindh').
location_of_formation('nichiren_sh_sh_', 'minobu').
location_of_formation('louisiana_voodoo', 'louisiana').
location_of_formation('spiritual_christianity', 'tsardom_of_russia').
location_of_formation('feri_tradition', 'california').
location_of_formation('arathi', 'kenya').
location_of_formation('arar__religion', 'cuba').
location_of_formation('zenith_applied_philosophy', 'christchurch').
location_of_formation('adat_musi', 'musi').
location_of_formation('sann_', 'hiyoshi_taisha').
official_religion('buddhism', 'bhutan').
official_religion('buddhism', 'myanmar').
official_religion('buddhism', 'sri_lanka').
official_religion('tengrism', 'list_of_tengrist_states_and_dynasties').
practiced_by('buddhism', 'sa_gha').
practiced_by('judaism', 'dayan').
practiced_by('judaism', 'rabbi').
practiced_by('taoism', 'daoshi').
practiced_by('taoism', 'taoist_nun').
practiced_by('taoism', 'taoist').
practiced_by('confucianism', 'confucian_scholar').
practiced_by('shamanism', 'shaman').
practiced_by('unitarianism', 'unitarian_pastor').
practiced_by('yazidism', 'yazidis').
practiced_by('germanic_paganism', 'germanic_peoples').
practiced_by('haymanot', 'beta_israel').
practiced_by('ignatian_spirituality', 'jesuit').
practiced_by('ecosophy', 'ecosopher').
location('hinduism', 'worldwide').
location('yoruba_religion', 'benin').
location('yoruba_religion', 'nigeria').
location('collyridianism', 'arabian_peninsula').
location('hypsistarians', 'asia_minor').
location('etruscan_religion', 'etruria').
location('religion_and_ritual_of_the_cucuteni_trypillian_culture', 'europe').
location('anupa', 'indian_subcontinent').
location('international_horse_procession_hakendover_tienen', 'hakendover').
location('native_american_religion_in_north_america', 'north_america').
location('pilgrim_s_table_at_saint_julian_s_hospital', 'antwerp').
location('st_anthony_s_day_celebrations_in_flanders', 'flanders').
location('st_mathew_s_anglican_church_maitama_abuja', 'nigeria').
location('gion_faith', 'gion_shrine').
location('tenjin_faith', 'tenmang_').
subclass_of('hinduism', 'state_religion').
subclass_of('hinduism', 'indian_religions').
subclass_of('taoism', 'religion').
subclass_of('taoism', 'philosophy').
subclass_of('zoroastrianism', 'dualistic_cosmology').
subclass_of('confucianism', 'eastern_philosophy').
subclass_of('bah____faith', 'abrahamic_religion').
subclass_of('animism', 'traditional_religion').
subclass_of('scientology', 'religious_movement').
subclass_of('modern_paganism', 'polytheism').
subclass_of('modern_paganism', 'idolatry').
subclass_of('modern_paganism', 'pantheism').
subclass_of('tengrism', 'ethnic_religion').
subclass_of('tengrism', 'folk_religion').
subclass_of('unitarianism', 'protestantism').
subclass_of('ancient_roman_religion', 'religion').
subclass_of('b_bism', 'abrahamic_religion').
subclass_of('chinese_folk_religion', 'folk_religion').
subclass_of('chinese_folk_religion', 'ethnic_religion').
subclass_of('rule_of_osha', 'if_').
subclass_of('gallicanism', 'catholicism').
subclass_of('brahmanism', 'hinduism').
subclass_of('yazidism', 'monotheistic_religion').
subclass_of('germanic_paganism', 'polytheism').
subclass_of('germanic_paganism', 'paganism').
subclass_of('modern_asatru', 'heathenry').
subclass_of('zurvanism', 'zoroastrianism').
subclass_of('atenism', 'religion_of_ancient_egypt').
subclass_of('heathenry', 'modern_paganism').
subclass_of('laveyan_satanism', 'satanism').
subclass_of('pastafarianism', 'monotheistic_religion').
subclass_of('canaanite_religion', 'ancient_semitic_religion').
subclass_of('kemetism', 'polytheistic_reconstructionism').
subclass_of('babylonian_religion', 'ancient_mesopotamian_religion').
subclass_of('hellenistic_judaism', 'second_temple_judaism').
subclass_of('ancient_mesopotamian_religion', 'religion').
subclass_of('samaritanism', 'religion').
subclass_of('samaritanism', 'monotheism').
subclass_of('kadam', 'sarma').
subclass_of('nichiren_sh_sh_', 'fuji_lineage').
subclass_of('grapevine_cross', 'christianity').
subclass_of('grapevine_cross', 'eastern_orthodox_church').
subclass_of('matha', 'organization').
subclass_of('matha', 'religious_complex').
subclass_of('drukpa_lineage', 'kagyu').
subclass_of('second_temple_judaism', 'judaism').
subclass_of('jewish_renewal', 'judaism').
subclass_of('haitian_vodou', 'voodoo_church').
subclass_of('haitian_vodou', 'afro_american_religion').
subclass_of('polytheistic_reconstructionism', 'modern_paganism').
subclass_of('aztec_religion', 'mesoamerican_religion').
subclass_of('theology_of_huldrych_zwingli', 'christianity').
subclass_of('sanamahism', 'animism').
subclass_of('sanamahism', 'spiritualism').
subclass_of('sanamahism', 'nature_worship').
subclass_of('sanamahism', 'polytheism').
subclass_of('sanamahism', 'shamanism').
subclass_of('sanamahism', 'paganism').
subclass_of('roman_polytheistic_reconstructionism', 'modern_paganism').
subclass_of('ryukyuan_religion', 'religion_in_ryukyu').
subclass_of('cross_and_crown', 'christianity').
subclass_of('native_american_religions', 'ethnic_religion').
subclass_of('surat_shabd_yoga', 'yoga').
subclass_of('louisiana_voodoo', 'black_church').
subclass_of('louisiana_voodoo', 'voodoo_church').
subclass_of('etruscan_religion', 'polytheistic_religion').
subclass_of('traditional_anglican_communion', 'christianity').
subclass_of('finnish_neopaganism', 'modern_paganism').
subclass_of('nicene_christianity', 'christianity').
subclass_of('nauruan_indigenous_religion', 'micronesian_mythology').
subclass_of('spiritual_christianity', 'eastern_christianity').
subclass_of('spiritual_christianity', 'christianity').
subclass_of('arab_muslims', 'arabs').
subclass_of('arab_muslims', 'muslim').
subclass_of('haymanot', 'judaism').
subclass_of('haymanot', 'history_of_the_jews_in_ethiopia').
subclass_of('hetanism', 'armenian_neopaganism').
subclass_of('yuzu_nembutsu', 'pure_land_buddhism').
subclass_of('yuzu_nembutsu', 'buddhism_in_japan').
subclass_of('primitive_baptists', 'baptists').
subclass_of('feri_tradition', 'modern_paganism').
subclass_of('feri_tradition', 'wicca').
subclass_of('abwoi_religion', 'african_traditional_religion__atr___a_proposal_for_academic_reflection').
subclass_of('ngor', 'sakya').
subclass_of('jeung_san_do', 'jeungsanism').
subclass_of('neo_theosophy', 'blavatskian_theosophy').
subclass_of('mapuche_religion', 'pre_columbian_mythology').
subclass_of('gonabadi_dervish', 'abrahamic_religion').
subclass_of('ignatian_spirituality', 'spirituality').
subclass_of('religious_confucianism', 'confucianism').
subclass_of('ugaritic_religion', 'canaanite_religion').
subclass_of('apokpa_marup', 'sanamahism').
subclass_of('heaven_worship', 'chinese_folk_religion').
subclass_of('kid_', 'shamanism').
subclass_of('episcopal_diocese_of_litoral_ecuador', 'church_of_england_parish_church').
subclass_of('amazighs_christians_donatians', 'berber').
subclass_of('amazighs_christians_donatians', 'christian').
subclass_of('visigothic_arianism', 'arianism').
subclass_of('ancestrality', 'group').
subclass_of('cosmotheism', 'religion').
subclass_of('asatru', 'old_norse_religion').
subclass_of('native_american_religion_in_north_america', 'belief_system').
subclass_of('native_american_religion_in_north_america', 'native_american_religions').
subclass_of('white_american_religion', 'religion_in_the_united_states').
subclass_of('samnite_religion', 'religion').
subclass_of('jeungsangyo_bonbu', 'jeungsanism').
subclass_of('lydian_religion', 'religion').
subclass_of('umbandism', 'spiritualism').
subclass_of('undenominationalism', 'christianity').
subclass_of('undenominationalism', 'organization').
subclass_of('undenominationalism', 'belief').
subclass_of('baalism', 'canaanite_religion').
subclass_of('wesenmystik', 'christian_mysticism').
subclass_of('franciscan_spirituality', 'spirituality').
subclass_of('syriac_orthodox_christianity', 'christianity').
subclass_of('sabine_religion', 'religion').
subclass_of('obscurantism', 'conservatism').
subclass_of('mind_body_dualism', 'dualism').
subclass_of('critical_rationalism', 'rationalism').
subclass_of('innatism', 'doctrine').
subclass_of('ecosophy', 'philosophy').
subclass_of('foundationalism', 'epistemology').
subclass_of('coherentism', 'epistemology').
subclass_of('spiritualism', 'philosophical_movement').
subclass_of('social_ecology', 'green_anarchism').
subclass_of('exceptionalism', 'political_ideology').
subclass_of('existential_nihilism', 'nihilism').
subclass_of('epistemic_injustice', 'injustice').
subclass_of('trivialism', 'dialetheism').
subclass_of('radical_behaviorism', 'behaviorism').
subclass_of('integral_humanism', 'humanism').
subclass_of('platonic_epistemology', 'epistemology').
subclass_of('semantic_theory_of_truth', 'theory_of_truth').
subclass_of('multiplicity', 'multiplicity').
subclass_of('infinitism', 'epistemology').
subclass_of('neohumanism', 'humanism').
subclass_of('structuralism', 'structuralism').
subclass_of('new_materialism', 'materialism').
subclass_of('existential_humanism', 'humanism').
subclass_of('existential_humanism', 'existentialism').
subclass_of('epistemological_solipsism', 'solipsism').
subclass_of('formal_innatism', 'innatism').
subclass_of('pantheistic_monism', 'pantheism').
subclass_of('pantheistic_monism', 'monism').
subclass_of('metaphysical_solipsism', 'subjective_idealism').
subclass_of('metaphysical_solipsism', 'solipsism').
subclass_of('astrolatry', 'nature_worship').
subclass_of('uwaisi', 'transfer').
subclass_of('gion_faith', 'shinbutsu_sh_g_').
subclass_of('tenjin_faith', 'shinto').
subclass_of('sann_', 'shinbutsu_sh_g_').
subclass_of('hikawa_shink_', 'shinto').
subclass_of('gory__faith', 'shinto').
partially_coincident_with('hinduism', 'culture_of_india').
partially_coincident_with('tengrism', 'modern_paganism').
partially_coincident_with('tengrism', 'new_religious_movement').
partially_coincident_with('samaritanism', 'samaritan').
partially_coincident_with('second_temple_judaism', 'history_of_the_jews_in_the_roman_empire').
partially_coincident_with('mari_religion', 'mari_mythology').
partially_coincident_with('collyridianism', 'mariolatry').
partially_coincident_with('mordvin_native_religion', 'mordvin_mythology').
partially_coincident_with('monism', 'indivisibility').
partially_coincident_with('uniformitarianism', 'gradualism').
partially_coincident_with('obscurantism', 'q11263220').
member_count('hinduism', '1200000000').
member_count('bah____faith', '6000000').
member_count('din_e_ilahi', '19').
member_count('makuya_church', '60000').
member_count('longhouse_religion', '5000').
member_count('psychedelic_venus_church', '700').
different_from('hinduism', 'indian_loanwords').
different_from('animism', 'animeism').
different_from('rastafari', 'rastafari').
different_from('rastafari', 'pastafarianism').
different_from('scientology', 'scientonomy').
different_from('scientology', 'religious_science').
different_from('catharism', 'cathare').
different_from('ancient_roman_religion', 'religion_in_ancient_rome').
different_from('ancient_roman_religion', 'religious_policies_of_the_roman_empire').
different_from('hanif', 'hanafism').
different_from('hanif', 'hanifiyya').
different_from('modern_asatru', 'asatru').
different_from('pastafarianism', 'rastafari').
different_from('homaranismo', 'humanism').
different_from('cult_of_reason', 'cult_of_the_supreme_being').
different_from('kadam', 'mount_kadam').
different_from('polytheistic_reconstructionism', 'historical_reenactment').
different_from('bori_religion', 'bori').
different_from('proto_indo_iranian_religion', 'persian_mythology').
different_from('earthseed', 'terasem_movement').
different_from('druzism', 'q163943').
different_from('terasem_movement', 'earthseed').
different_from('asatru', 'modern_asatru').
different_from('aluk_todolo', 'aluk_todolo').
different_from('monism', 'monad').
different_from('fatalism', 'defeatism').
different_from('nominalism', 'q11792771').
different_from('uniformitarianism', 'actualism').
different_from('uniformitarianism', 'uniform').
different_from('sensationism', 'sensationalism').
different_from('pluralism', 'pluralism').
different_from('conceptualism', 'conceptual_art').
different_from('innatism', 'innateness_hypothesis').
different_from('innatism', 'psychological_nativism').
different_from('innatism', 'nativism').
different_from('compatibilism', 'religious_naturalism').
different_from('spiritualism', 'spiritualism').
different_from('social_ecology', 'social_ecology').
different_from('social_ecology', 'social_ecology').
different_from('double_truth', 'two_truths_doctrine').
different_from('probabilism', 'catholic_probabilism').
different_from('actualism', 'uniformitarianism').
different_from('best_of_all_possible_worlds', 'optimism').
different_from('trivialism', 'dialetheism').
different_from('animalism', 'animism').
different_from('animalism', 'animalism').
different_from('neo_idealism', 'neo_idealism').
different_from('uwaisi', 'uwaisi').
has_part_s_('hinduism', 'hindu_denomination').
has_part_s_('confucianism', 'confucianism_in_indonesia').
has_part_s_('confucianism', 'korean_confucianism').
has_part_s_('confucianism', 'confucianism_in_japan').
has_part_s_('confucianism', 'neo_confucianism').
has_part_s_('religion_of_ancient_egypt', 'egyptian_mythology').
has_part_s_('thelema', 'choronzon').
has_part_s_('sumerian_religion', 'ancient_mesopotamian_religion').
has_part_s_('canaanite_religion', 'ugaritic_religion').
has_part_s_('canaanite_religion', 'canaanite_mythology').
has_part_s_('anglo_catholicism', 'liberal_anglo_catholicism').
has_part_s_('aztec_religion', 'aztec_calendar').
has_part_s_('aztec_religion', 'aztec_mythology').
has_part_s_('native_american_religions', 'native_american_religion_in_central_america').
has_part_s_('native_american_religions', 'native_american_religion_in_south_america').
has_part_s_('native_american_religions', 'native_american_religion_in_the_caribbean').
has_part_s_('native_american_religions', 'native_american_religion_in_north_america').
has_part_s_('etruscan_religion', 'etruscan_mythology').
has_part_s_('mesoamerican_religion', 'aztec_religion').
has_part_s_('mesoamerican_religion', 'maya_religion').
has_part_s_('__o_m_u', 'l_n___ng').
has_part_s_('ugaritic_religion', 'baal_cycle').
has_part_s_('ugaritic_religion', 'ugaritic_mythology').
has_part_s_('native_american_religion_in_north_america', 'native_american_religion_in_the_united_states').
has_part_s_('monism', 'materialism').
has_part_s_('monism', 'idealism').
has_part_s_('monism', 'neutral_monism').
has_part_s_('el_cantare', 'elohim').
has_part_s_('el_cantare', 'ry_h___kawa').
foundational_text('hinduism', 'vedas').
foundational_text('zoroastrianism', 'avesta').
foundational_text('catharism', 'new_testament').
foundational_text('laveyan_satanism', 'the_satanic_bible').
foundational_text('pastafarianism', 'the_gospel_of_the_flying_spaghetti_monster').
represented_by('judaism', 'jewish_religious_community').
permanent_duplicated_item('judaism', 'jewish_religion').
permanent_duplicated_item('taoism', 'q22827771').
permanent_duplicated_item('confucianism', 'q22828627').
permanent_duplicated_item('monism', 'q60978420').
has_list('judaism', 'list_of_jewish_communities_by_country').
has_list('modern_paganism', 'list_of_modern_pagan_temples').
has_list('modern_paganism', 'list_of_neopagan_movements').
has_list('tengrism', 'list_of_tengrist_states_and_dynasties').
has_list('tengrism', 'list_of_tengrist_movements').
operating_area('judaism', 'worldwide').
founded_by('taoism', 'laozi').
founded_by('zoroastrianism', 'zoroaster').
founded_by('jainism', 'rishabhanatha').
founded_by('jainism', 'parshvanatha').
founded_by('jainism', 'mahavira').
founded_by('bah____faith', 'bah__u_ll_h').
founded_by('scientology', 'l__ron_hubbard').
founded_by('b_bism', 'b_b').
founded_by('din_e_ilahi', 'akbar').
founded_by('yazidism', 'adi_ibn_musafir').
founded_by('discordianism', 'malaclypse_the_younger').
founded_by('discordianism', 'kerry_wendell_thornley').
founded_by('soka_gakkai', 'j_sei_toda').
founded_by('soka_gakkai', 'tsunesabur__makiguchi').
founded_by('laveyan_satanism', 'anton_lavey').
founded_by('pastafarianism', 'bobby_henderson').
founded_by('umbanda', 'z_lio_fernandino_de_moraes').
founded_by('eckankar', 'paul_twitchell').
founded_by('nichiren_sh_sh_', 'nissh_').
founded_by('theology_of_huldrych_zwingli', 'huldrych_zwingli').
founded_by('coconut_religion', 'nguy_n_thanh_nam').
founded_by('feri_tradition', 'victor_henry_anderson').
founded_by('feri_tradition', 'cora_anderson').
founded_by('ngor', 'ngorchen_kunga_zangpo').
founded_by('midewiwin', 'nanabozho').
founded_by('midewiwin', 'jiibayaabooz').
founded_by('jeung_san_do', 'ahn_se_chan').
founded_by('church_universal_and_triumphant', 'elizabeth_clare_prophet').
founded_by('gonabadi_dervish', 'shah_nimatullah_wali').
founded_by('ignatian_spirituality', 'ignatius_of_loyola').
founded_by('mundial_church_of_god_s_power', 'valdemiro_santiago').
founded_by('longhouse_religion', 'handsome_lake').
founded_by('international_peace_mission_movement', 'father_divine').
founded_by('the_new_church', 'emmanuel_swedenborg').
founded_by('emissaries_of_divine_light', 'lloyd_arthur_meeker').
founded_by('zenith_applied_philosophy', 'john_dalhoff').
founded_by('terasem_movement', 'martine_rothblatt').
founded_by('winningjahrian', 'winning_jah').
founded_by('c3woc', 'l3d').
founded_by('umbandism', 'z_lio_fernandino_de_moraes').
founded_by('om_lovers', 'william_brumfield').
founded_by('psychedelic_venus_church', 'jefferson_poland').
founded_by('neohumanism', 'prabhat_rainjan_sarkar').
founded_by('uwaisi', 'uwais_qarni').
instance_of('taoism', 'philosophical_movement').
instance_of('taoism', 'religion').
instance_of('zoroastrianism', 'religion').
instance_of('jainism', 'religion').
instance_of('bah____faith', 'religion').
instance_of('animism', 'religion').
instance_of('animism', 'religion_type').
instance_of('shamanism', 'religion').
instance_of('rastafari', 'ideology').
instance_of('rastafari', 'religion').
instance_of('rastafari', 'social_movement').
instance_of('scientology', 'religion').
instance_of('scientology', 'new_religious_movement').
instance_of('catharism', 'religion').
instance_of('catharism', 'religious_movement').
instance_of('religion_of_ancient_egypt', 'religion').
instance_of('modern_paganism', 'world_view').
instance_of('modern_paganism', 'new_religious_movement').
instance_of('modern_paganism', 'religion').
instance_of('tengrism', 'religion').
instance_of('unitarianism', 'religion').
instance_of('unitarianism', 'religious_denomination').
instance_of('ancient_roman_religion', 'religion').
instance_of('b_bism', 'religion').
instance_of('historical_vedic_religion', 'religion').
instance_of('historical_vedic_religion', 'rite').
instance_of('chinese_folk_religion', 'religion').
instance_of('thelema', 'religion').
instance_of('yarsanism', 'tariqa').
instance_of('yarsanism', 'religion').
instance_of('sumerian_religion', 'mythology').
instance_of('sumerian_religion', 'religion').
instance_of('arminianism', 'christian_theological_school').
instance_of('arminianism', 'religion').
instance_of('rule_of_osha', 'religion').
instance_of('rule_of_osha', 'rite').
instance_of('gallicanism', 'political_theory').
instance_of('gallicanism', 'religion').
instance_of('gallicanism', 'christian_denomination').
instance_of('hanif', 'belief').
instance_of('hanif', 'religion').
instance_of('brahmanism', 'religion').
instance_of('din_e_ilahi', 'religion').
instance_of('yazidism', 'religion').
instance_of('discordianism', 'religion').
instance_of('discordianism', 'parody_religion').
instance_of('germanic_paganism', 'germanic_religion').
instance_of('germanic_paganism', 'religion').
instance_of('modern_asatru', 'religion').
instance_of('soka_gakkai', 'religious_organization').
instance_of('soka_gakkai', 'religion').
instance_of('zurvanism', 'religion').
instance_of('proto_indo_european_mythology', 'religion').
instance_of('proto_indo_european_mythology', 'mythology').
instance_of('atenism', 'monotheism').
instance_of('atenism', 'religion').
instance_of('heathenry', 'religion').
instance_of('laveyan_satanism', 'fictional_religion').
instance_of('laveyan_satanism', 'religion').
instance_of('pastafarianism', 'religion').
instance_of('pastafarianism', 'religious_satire').
instance_of('pastafarianism', 'parody_religion').
instance_of('yoruba_religion', 'religion').
instance_of('canaanite_religion', 'mythology').
instance_of('canaanite_religion', 'religion').
instance_of('homaranismo', 'religion').
instance_of('homaranismo', 'ideology').
instance_of('anglo_catholicism', 'religion').
instance_of('anglo_catholicism', 'school_of_thought').
instance_of('kemetism', 'religion').
instance_of('kemetism', 'new_religious_movement').
instance_of('cult_of_reason', 'state_atheism').
instance_of('cult_of_reason', 'religion').
instance_of('babylonian_religion', 'religion').
instance_of('umbanda', 'religion').
instance_of('hellenistic_judaism', 'religion').
instance_of('ancient_mesopotamian_religion', 'mythology').
instance_of('ancient_mesopotamian_religion', 'religion').
instance_of('australian_aboriginal_mythology', 'religion').
instance_of('australian_aboriginal_mythology', 'ritual').
instance_of('australian_aboriginal_mythology', 'mythology').
instance_of('eckankar', 'religion').
instance_of('native_american_church', 'religion').
instance_of('ariosophy', 'pseudoscience').
instance_of('ariosophy', 'religion').
instance_of('ariosophy', 'ideology').
instance_of('samaritanism', 'abrahamic_religion').
instance_of('samaritanism', 'religion').
instance_of('kadam', 'religion').
instance_of('kadam', 'school_of_buddhism').
instance_of('if_', 'religion').
instance_of('sallekhana', 'spiritual_practice').
instance_of('sallekhana', 'religion').
instance_of('nichiren_sh_sh_', 'religion').
instance_of('nichiren_sh_sh_', 'school_of_buddhism').
instance_of('grapevine_cross', 'religion').
instance_of('matha', 'religious_complex').
instance_of('matha', 'religion').
instance_of('matha', 'structure_of_worship').
instance_of('matha', 'monastery').
instance_of('matha', 'institute').
instance_of('sarnaism', 'indian_religions').
instance_of('sarnaism', 'religion').
instance_of('sarnaism', 'lifestyle').
instance_of('sarnaism', 'culture').
instance_of('drukpa_lineage', 'school_of_buddhism').
instance_of('drukpa_lineage', 'religion').
instance_of('low_church', 'social_category').
instance_of('low_church', 'religion').
instance_of('punic_religion', 'religion').
instance_of('theophilanthropy', 'religion').
instance_of('religion_of_humanity', 'religion').
instance_of('second_temple_judaism', 'religion').
instance_of('second_temple_judaism', 'historical_period').
instance_of('jewish_renewal', 'religion').
instance_of('jewish_renewal', 'jewish_religious_movements').
instance_of('haitian_vodou', 'religion').
instance_of('bwiti', 'religion').
instance_of('gardnerian_wicca', 'religion').
instance_of('traditional_berber_religion', 'religion').
instance_of('polytheistic_reconstructionism', 'religion').
instance_of('aztec_religion', 'ethnic_religion').
instance_of('aztec_religion', 'religion').
instance_of('mari_religion', 'religion').
instance_of('santo_daime', 'new_religious_movement').
instance_of('santo_daime', 'religion').
instance_of('theology_of_huldrych_zwingli', 'religion').
instance_of('collyridianism', 'religion').
instance_of('collyridianism', 'christian_denomination').
instance_of('sanamahism', 'religion').
instance_of('sanamahism', 'religious_movement').
instance_of('roman_polytheistic_reconstructionism', 'religion').
instance_of('winti', 'religion').
instance_of('coconut_religion', 'religion').
instance_of('ryukyuan_religion', 'religion').
instance_of('cross_and_crown', 'religion').
instance_of('daoyuan', 'religion').
instance_of('gottgl_ubig', 'religion').
instance_of('modekngei', 'religion').
instance_of('palo_mayombe', 'religion').
instance_of('native_american_religions', 'religion').
instance_of('surat_shabd_yoga', 'religion').
instance_of('detachment', 'concept').
instance_of('detachment', 'religion').
instance_of('detachment', 'philosophy').
instance_of('hypsistarians', 'religion').
instance_of('louisiana_voodoo', 'religion').
instance_of('brahmoism', 'religion').
instance_of('etruscan_religion', 'religion').
instance_of('traditional_anglican_communion', 'religion').
instance_of('bori_religion', 'religion').
instance_of('finnish_neopaganism', 'religion').
instance_of('proto_indo_iranian_religion', 'religion').
instance_of('makuya_church', 'religion').
instance_of('nicene_christianity', 'religion').
instance_of('mazdaism', 'religion').
instance_of('nauruan_indigenous_religion', 'religion').
instance_of('spiritual_christianity', 'religion').
instance_of('spiritual_christianity', 'religious_movement').
instance_of('donyi_polo', 'religion').
instance_of('arab_muslims', 'isolated_human_group').
instance_of('arab_muslims', 'ethnic_group').
instance_of('arab_muslims', 'nationality').
instance_of('arab_muslims', 'nation').
instance_of('arab_muslims', 'people').
instance_of('arab_muslims', 'ethnic_community').
instance_of('arab_muslims', 'religion').
instance_of('arab_muslims', 'world_view').
instance_of('haymanot', 'religion').
instance_of('judaism_s_view_on_muhammad', 'religion').
instance_of('hetanism', 'religion').
instance_of('gallo_roman_religion', 'religion').
instance_of('yuzu_nembutsu', 'religion').
instance_of('badimo', 'religion').
instance_of('akan_religion', 'religion').
instance_of('elamite_religion', 'religion').
instance_of('elamite_religion', 'world_view').
instance_of('antonianism', 'religion').
instance_of('adi_dharm', 'religion').
instance_of('primitive_baptists', 'religion').
instance_of('primitive_baptists', 'christian_organization').
instance_of('mango_worship', 'cult').
instance_of('mango_worship', 'religion').
instance_of('wetu_telu_thoriqoh', 'religion').
instance_of('feri_tradition', 'religion').
instance_of('feri_tradition', 'religious_denomination').
instance_of('hittite_religion', 'religion').
instance_of('tai_folk_religion', 'folk_culture').
instance_of('tai_folk_religion', 'folk_religion').
instance_of('tai_folk_religion', 'religion').
instance_of('tai_folk_religion', 'polytheistic_religion').
instance_of('religion_in_space', 'spaceflight').
instance_of('religion_in_space', 'religion').
instance_of('mordvin_native_religion', 'religion').
instance_of('nabataean_religion', 'religion').
instance_of('muisca_religion', 'religion').
instance_of('abwoi_religion', 'religion').
instance_of('ngor', 'religion').
instance_of('midewiwin', 'society').
instance_of('midewiwin', 'religion').
instance_of('jeung_san_do', 'religion').
instance_of('pai_m_rire', 'religion').
instance_of('bimoism', 'religion').
instance_of('neo_theosophy', 'religion').
instance_of('mapuche_religion', 'mythology').
instance_of('mapuche_religion', 'religion').
instance_of('mesoamerican_religion', 'religion').
instance_of('urreligion', 'religion').
instance_of('church_universal_and_triumphant', 'religious_denomination').
instance_of('church_universal_and_triumphant', 'religion').
instance_of('gonabadi_dervish', 'religion').
instance_of('gnostic_church_of_france', 'organization').
instance_of('gnostic_church_of_france', 'religion').
instance_of('madhwa_brahmins', 'religion').
instance_of('universalist_church_of_america', 'religion').
instance_of('universalist_church_of_america', 'organization').
instance_of('tensh__k_tai_jing_ky_', 'religion').
instance_of('harrisme', 'religion').
instance_of('__o_m_u', 'religion').
instance_of('__o_m_u', 'religion_in_vietnam').
instance_of('__o_m_u', 'vietnamese_folk_religion').
instance_of('ignatian_spirituality', 'religion').
instance_of('ignatian_spirituality', 'activity').
instance_of('mundial_church_of_god_s_power', 'religion').
instance_of('longhouse_religion', 'religion').
instance_of('religious_confucianism', 'religion').
instance_of('svetosavlje', 'religion').
instance_of('ground_crew_project', 'religion').
instance_of('ahom_religion', 'religion').
instance_of('mun', 'religion').
instance_of('ugaritic_religion', 'religion').
instance_of('beliefs_and_practices_of_the_church_of_jesus_christ_of_latter_day_saints', 'religion').
instance_of('international_peace_mission_movement', 'religion').
instance_of('religion_and_ritual_of_the_cucuteni_trypillian_culture', 'religion').
instance_of('religion_and_ritual_of_the_cucuteni_trypillian_culture', 'archaeological_culture').
instance_of('igreja_crist__maranata', 'church_congregation').
instance_of('igreja_crist__maranata', 'religion').
instance_of('kalash_religion', 'religion').
instance_of('anupa', 'religion').
instance_of('apokpa_marup', 'religion').
instance_of('arathi', 'religion').
instance_of('brahmo', 'religion').
instance_of('church_of_aphrodite', 'religion').
instance_of('heaven_worship', 'religion').
instance_of('preanimism', 'religion').
instance_of('nyoraikyo', 'religion').
instance_of('kid_', 'religion').
instance_of('episcopal_diocese_of_litoral_ecuador', 'religion').
instance_of('hanolgyo', 'religion').
instance_of('amazighs_christians_donatians', 'ethnic_group').
instance_of('amazighs_christians_donatians', 'religion').
instance_of('african_religion', 'religion').
instance_of('ashurism', 'religion').
instance_of('bell_church', 'religion').
instance_of('bell_church', 'organization').
instance_of('jamaican_maroon_religion', 'religion').
instance_of('daijokyo', 'religion').
instance_of('arar__religion', 'religion').
instance_of('meiteism', 'religion').
instance_of('meiteism', 'religious_movement').
instance_of('efik_religion', 'religion').
instance_of('kushite_religion', 'religion').
instance_of('international_horse_procession_hakendover_tienen', 'religion').
instance_of('international_horse_procession_hakendover_tienen', 'drinking').
instance_of('international_horse_procession_hakendover_tienen', 'nature').
instance_of('international_horse_procession_hakendover_tienen', 'landscape').
instance_of('international_horse_procession_hakendover_tienen', 'ritual').
instance_of('international_horse_procession_hakendover_tienen', 'party').
instance_of('international_horse_procession_hakendover_tienen', 'parade').
instance_of('international_horse_procession_hakendover_tienen', 'animal').
instance_of('international_horse_procession_hakendover_tienen', 'agriculture').
instance_of('international_horse_procession_hakendover_tienen', 'custom').
instance_of('international_horse_procession_hakendover_tienen', 'eating').
instance_of('lamoa', 'religion').
instance_of('the_new_church', 'religion').
instance_of('vianova', 'religion').
instance_of('vianova', 'organization').
instance_of('kabyle_mythology', 'religion').
instance_of('natib_qadish', 'religion').
instance_of('earthseed', 'religion').
instance_of('emissaries_of_divine_light', '501_c__3__organization').
instance_of('emissaries_of_divine_light', 'religion').
instance_of('emissaries_of_divine_light', 'religious_organization').
instance_of('emissaries_of_divine_light', 'sect').
instance_of('knights_of_seth', 'religion').
instance_of('knights_of_seth', 'society').
instance_of('laestadianism_in_america', 'religious_denomination').
instance_of('laestadianism_in_america', 'religion').
instance_of('pelebegu', 'religion').
instance_of('temple_of_the_true_inner_light', 'religion').
instance_of('zenith_applied_philosophy', 'religion').
instance_of('zenith_applied_philosophy', 'new_religious_movement').
instance_of('zenith_applied_philosophy', 'religious_organization').
instance_of('zenith_applied_philosophy', 'educational_organization').
instance_of('visigothic_arianism', 'religion').
instance_of('ancestrality', 'religion').
instance_of('druzism', 'religion').
instance_of('druzism', 'religious_order').
instance_of('druzism', 'madhhab').
instance_of('cosmotheism', 'philosophical_movement').
instance_of('cosmotheism', 'sect').
instance_of('cosmotheism', 'world_view').
instance_of('cosmotheism', 'religion').
instance_of('terasem_movement', 'group').
instance_of('terasem_movement', 'community').
instance_of('terasem_movement', 'religion').
instance_of('kingdom_movement', 'religion').
instance_of('sun_descendants', 'religion').
instance_of('daba', 'religion').
instance_of('asatru', 'religion').
instance_of('aluk_todolo', 'religion').
instance_of('ancient_druidism', 'religion').
instance_of('gwanseonggyo', 'religion').
instance_of('houkoukai', 'religion').
instance_of('dogon_religion', 'religion').
instance_of('adat_musi', 'agama_asli_nusantara').
instance_of('adat_musi', 'religion').
instance_of('native_american_religion_in_north_america', 'religion').
instance_of('white_american_religion', 'religion').
instance_of('samnite_religion', 'religion').
instance_of('dunamis_international_gospel_centre', 'religion').
instance_of('jeungsangyo_bonbu', 'religion').
instance_of('leke', 'religion').
instance_of('hlai_folk_religion', 'religion').
instance_of('religion_of_sakalava_people', 'religion').
instance_of('sari_dharam', 'religion').
instance_of('lydian_religion', 'religion').
instance_of('winningjahrian', 'religion').
instance_of('big_drum', 'society').
instance_of('big_drum', 'religion').
instance_of('c3woc', 'religion').
instance_of('c3woc', 'nonprofit_organization').
instance_of('umbandism', 'religion').
instance_of('umbandism', 'religious_movement').
instance_of('hangui', 'religion').
instance_of('undenominationalism', 'religion').
instance_of('baalism', 'religion').
instance_of('wesenmystik', 'religion').
instance_of('franciscan_spirituality', 'religion').
instance_of('traditional_choctaw_religion', 'religion').
instance_of('syriac_orthodox_christianity', 'religion').
instance_of('sabine_religion', 'religion').
instance_of('pilgrim_s_table_at_saint_julian_s_hospital', 'eating').
instance_of('pilgrim_s_table_at_saint_julian_s_hospital', 'ritual').
instance_of('pilgrim_s_table_at_saint_julian_s_hospital', 'religion').
instance_of('pilgrim_s_table_at_saint_julian_s_hospital', 'custom').
instance_of('st_anthony_s_day_celebrations_in_flanders', 'eating').
instance_of('st_anthony_s_day_celebrations_in_flanders', 'custom').
instance_of('st_anthony_s_day_celebrations_in_flanders', 'drinking').
instance_of('st_anthony_s_day_celebrations_in_flanders', 'party').
instance_of('st_anthony_s_day_celebrations_in_flanders', 'animal').
instance_of('st_anthony_s_day_celebrations_in_flanders', 'religion').
instance_of('st_anthony_s_day_celebrations_in_flanders', 'parade').
instance_of('philistine_religion', 'religion').
instance_of('phoenician_religion', 'religion').
instance_of('phoenician_religion', 'polytheistic_religion').
instance_of('phoenician_religion', 'ancient_semitic_religion').
instance_of('om_lovers', 'religion').
instance_of('om_lovers', 'religious_organization').
instance_of('om_lovers', 'new_religious_movement').
instance_of('psychedelic_venus_church', 'religion').
instance_of('psychedelic_venus_church', 'new_religious_movement').
instance_of('psychedelic_venus_church', 'religious_organization').
instance_of('sibook', 'scientific_journal').
instance_of('sibook', 'social').
instance_of('sibook', 'teacher').
instance_of('sibook', 'religion').
instance_of('st_mathew_s_anglican_church_maitama_abuja', 'religion').
instance_of('dahnhak', 'religion').
instance_of('muhammad_s_a_w_from_hira_cave_to_makkah', 'religion').
instance_of('muhammad_s_a_w_from_hira_cave_to_makkah', 'islam').
instance_of('muhammad_s_a_w_from_hira_cave_to_makkah', 'muslim').
instance_of('monism', 'theory').
instance_of('monism', 'concept').
instance_of('monism', 'philosophical_theory').
instance_of('monism', 'philosophical_movement').
instance_of('platonism', 'philosophical_theory').
instance_of('platonism', 'philosophical_school').
instance_of('fatalism', 'philosophical_theory').
instance_of('nominalism', 'philosophical_theory').
instance_of('uniformitarianism', 'principle').
instance_of('uniformitarianism', 'philosophical_theory').
instance_of('sensationism', 'philosophical_theory').
instance_of('sensationism', 'philosophical_movement').
instance_of('obscurantism', 'political_ideology').
instance_of('obscurantism', 'philosophical_theory').
instance_of('physicalism', 'philosophical_theory').
instance_of('pluralism', 'school_of_thought').
instance_of('pluralism', 'philosophical_theory').
instance_of('hylozoism', 'philosophical_theory').
instance_of('irrationalism', 'philosophical_theory').
instance_of('conceptualism', 'philosophical_theory').
instance_of('mind_body_dualism', 'philosophical_theory').
instance_of('psychologism', 'philosophical_theory').
instance_of('hylomorphism', 'philosophical_theory').
instance_of('critical_rationalism', 'philosophical_theory').
instance_of('euhemerism', 'philosophical_theory').
instance_of('epiphenomenalism', 'philosophical_theory').
instance_of('acosmism', 'philosophical_theory').
instance_of('innatism', 'philosophical_concept').
instance_of('innatism', 'philosophical_theory').
instance_of('transcendental_idealism', 'philosophical_theory').
instance_of('na_ve_realism', 'philosophical_theory').
instance_of('compatibilism', 'philosophical_theory').
instance_of('logical_atomism', 'philosophical_theory').
instance_of('logical_atomism', 'doctrine').
instance_of('eliminative_materialism', 'philosophical_theory').
instance_of('eliminative_materialism', 'materialism').
instance_of('ecosophy', 'academic_discipline').
instance_of('ecosophy', 'philosophical_theory').
instance_of('foundationalism', 'philosophical_theory').
instance_of('coherentism', 'philosophical_theory').
instance_of('conventionalism', 'philosophical_theory').
instance_of('eternalism', 'philosophical_theory').
instance_of('spiritualism', 'philosophical_theory').
instance_of('social_ecology', 'philosophical_theory').
instance_of('formalism', 'philosophical_theory').
instance_of('contractualism', 'political_theory').
instance_of('contractualism', 'philosophical_theory').
instance_of('metaphysical_naturalism', 'philosophical_theory').
instance_of('duhem_quine_thesis', 'philosophical_theory').
instance_of('platonic_realism', 'philosophical_theory').
instance_of('exceptionalism', 'philosophical_theory').
instance_of('right_to_the_city', 'philosophical_theory').
instance_of('parallelism', 'philosophical_theory').
instance_of('double_truth', 'philosophical_theory').
instance_of('neutral_monism', 'philosophical_theory').
instance_of('existential_nihilism', 'philosophical_theory').
instance_of('probabilism', 'philosophical_theory').
instance_of('meliorism', 'philosophical_theory').
instance_of('meliorism', 'ethical_concept').
instance_of('meliorism', 'principle').
instance_of('epistemic_injustice', 'philosophical_theory').
instance_of('actualism', 'philosophical_theory').
instance_of('modal_realism', 'philosophical_theory').
instance_of('cosmic_pluralism', 'philosophical_theory').
instance_of('best_of_all_possible_worlds', 'philosophical_concept').
instance_of('best_of_all_possible_worlds', 'philosophical_theory').
instance_of('antihumanism', 'philosophical_theory').
instance_of('decisionism', 'philosophical_theory').
instance_of('postanalytic_philosophy', 'philosophical_theory').
instance_of('dynamism', 'philosophical_theory').
instance_of('interactionism', 'philosophical_theory').
instance_of('anomalous_monism', 'philosophical_theory').
instance_of('property_dualism', 'philosophical_theory').
instance_of('corpuscularianism', 'philosophical_theory').
instance_of('corpuscularianism', 'physical_theory').
instance_of('perdurantism', 'philosophical_theory').
instance_of('emergentism', 'philosophical_theory').
instance_of('trope_theory', 'philosophical_theory').
instance_of('multiple_realizability', 'philosophical_theory').
instance_of('turtles_all_the_way_down', 'philosophical_theory').
instance_of('turtles_all_the_way_down', 'theory').
instance_of('turtles_all_the_way_down', 'hypothesis').
instance_of('turtles_all_the_way_down', 'philosophical_argument').
instance_of('trivialism', 'philosophical_theory').
instance_of('radical_behaviorism', 'philosophical_theory').
instance_of('occamism', 'philosophical_theory').
instance_of('integral_humanism', 'philosophical_theory').
instance_of('integral_humanism', 'political_ideology').
instance_of('supposition_theory', 'philosophical_theory').
instance_of('lockean_proviso', 'philosophical_theory').
instance_of('platonic_epistemology', 'philosophical_theory').
instance_of('marx_s_theory_of_human_nature', 'philosophical_theory').
instance_of('biological_naturalism', 'philosophical_theory').
instance_of('bundle_theory', 'philosophical_theory').
instance_of('semantic_theory_of_truth', 'philosophical_theory').
instance_of('labor_theory_of_property_acquisition', 'philosophical_theory').
instance_of('multiplicity', 'philosophical_theory').
instance_of('moderate_realism', 'philosophical_theory').
instance_of('b_theory_of_time', 'philosophical_theory').
instance_of('temporal_finitism', 'philosophical_theory').
instance_of('reconstructivism', 'philosophical_theory').
instance_of('infinitism', 'philosophical_theory').
instance_of('moral_sense_theory', 'philosophical_theory').
instance_of('neohumanism', 'school_of_thought').
instance_of('neohumanism', 'philosophical_theory').
instance_of('animalism', 'philosophical_theory').
instance_of('platonic_idealism', 'philosophical_theory').
instance_of('erastianism', 'philosophical_theory').
instance_of('epistemological_idealism', 'philosophical_theory').
instance_of('epistemological_particularism', 'philosophical_theory').
instance_of('metaphysical_nihilism', 'philosophical_theory').
instance_of('innate_goodness', 'doctrine').
instance_of('innate_goodness', 'theory').
instance_of('innate_goodness', 'philosophical_theory').
instance_of('innate_evilness', 'doctrine').
instance_of('innate_evilness', 'theory').
instance_of('innate_evilness', 'philosophical_theory').
instance_of('scientific_pluralism', 'philosophical_theory').
instance_of('solomonoff_s_theory_of_inductive_inference', 'philosophical_theory').
instance_of('logical_determinism', 'philosophical_theory').
instance_of('agential_realism', 'philosophical_theory').
instance_of('transcendental_analytic', 'philosophical_theory').
instance_of('aggressionism', 'philosophical_theory').
instance_of('structuralism', 'philosophical_theory').
instance_of('casualism', 'philosophical_theory').
instance_of('new_materialism', 'philosophical_theory').
instance_of('neorationalism', 'philosophical_theory').
instance_of('doctrine_of_internal_relations', 'philosophical_theory').
instance_of('existential_humanism', 'philosophical_theory').
instance_of('projectivism', 'philosophical_theory').
instance_of('thought_of_thomas_aquinas', 'philosophical_theory').
instance_of('epistemological_solipsism', 'philosophical_theory').
instance_of('perspectival_realism', 'philosophical_theory').
instance_of('logical_pluralism', 'philosophical_theory').
instance_of('justificationism', 'philosophical_theory').
instance_of('technocommunism', 'philosophical_theory').
instance_of('philosophical_thought_of_schopenhauer', 'philosophical_theory').
instance_of('formal_innatism', 'philosophical_concept').
instance_of('formal_innatism', 'philosophical_theory').
instance_of('pantheistic_monism', 'philosophical_theory').
instance_of('compensationism', 'philosophical_theory').
instance_of('formative_epistemology', 'philosophical_theory').
instance_of('metaphysical_solipsism', 'philosophical_theory').
instance_of('foundherentism', 'philosophical_theory').
instance_of('legitimacy', 'philosophical_theory').
instance_of('neo_idealism', 'philosophical_theory').
instance_of('receptivity', 'philosophical_theory').
instance_of('horak_controversy', 'controversy').
instance_of('horak_controversy', 'philosophical_theory').
instance_of('humean_definition_of_causality', 'philosophical_theory').
instance_of('correlationism', 'philosophical_theory').
instance_of('voice_of_poetry', 'philosophical_theory').
instance_of('mou_zongsan_s_moral_metaphysics', 'philosophical_theory').
instance_of('static_interpretation_of_time', 'philosophical_theory').
instance_of('predicativism', 'philosophical_theory').
instance_of('hylemorphic_dualism', 'philosophical_theory').
instance_of('historical_cycles', 'philosophical_theory').
instance_of('enlightenmentism', 'philosophical_theory').
instance_of('enlightenmentism', 'political_ideology').
instance_of('afterlife', 'biblical_concept').
instance_of('afterlife', 'faith').
instance_of('israelites_as_the_chosen_people', 'faith').
instance_of('israelites_as_the_chosen_people', 'exceptionalism').
instance_of('astrolatry', 'faith').
instance_of('uwaisi', 'faith').
instance_of('uwaisi', 'silsila').
instance_of('gion_faith', 'faith').
instance_of('tenjin_faith', 'faith').
instance_of('tenjin_faith', 'cult').
instance_of('el_cantare', 'theonym').
instance_of('el_cantare', 'faith').
instance_of('el_cantare', 'god').
instance_of('sann_', 'faith').
instance_of('hikawa_shink_', 'faith').
instance_of('seish_k__faith', 'faith').
instance_of('seish_k__faith', 'cult').
instance_of('seish_k__faith', 'apotheosis').
instance_of('taishi_cult', 'cult').
instance_of('taishi_cult', 'faith').
instance_of('gory__faith', 'faith').
main_regulatory_text('taoism', 'tao_te_ching').
main_regulatory_text('zoroastrianism', 'avesta').
main_regulatory_text('catharism', 'new_testament').
country_of_origin('taoism', 'china').
country_of_origin('arminianism', 'dutch_republic').
country_of_origin('rule_of_osha', 'brazil').
country_of_origin('soka_gakkai', 'japan').
country_of_origin('atenism', 'ancient_egypt').
country_of_origin('if_', 'nigeria').
country_of_origin('sanamahism', 'kingdom_of_manipur').
country_of_origin('ryukyuan_religion', 'ryukyu_kingdom').
country_of_origin('adi_dharm', 'india').
country_of_origin('international_peace_mission_movement', 'united_states_of_america').
country_of_origin('meiteism', 'kingdom_of_manipur').
country_of_origin('zenith_applied_philosophy', 'new_zealand').
country_of_origin('aluk_todolo', 'indonesia').
country_of_origin('gwanseonggyo', 'south_korea').
country_of_origin('umbandism', 'brazil').
country_of_origin('sibook', 'indonesia').
country_of_origin('sibook', 'west_java').
country_of_origin('sibook', 'banjar').
country_of_origin('dahnhak', 'south_korea').
country_of_origin('horak_controversy', 'joseon').
country('zoroastrianism', 'uzbekistan').
country('zoroastrianism', 'kurdistan_region').
country('zoroastrianism', 'united_states_of_america').
country('zoroastrianism', 'iran').
country('zoroastrianism', 'canada').
country('zoroastrianism', 'india').
country('zoroastrianism', 'tajikistan').
country('gallicanism', 'kingdom_of_france').
country('gallicanism', 'france').
country('din_e_ilahi', 'mughal_empire').
country('yazidism', 'turkey').
country('yazidism', 'iraq').
country('yazidism', 'syria').
country('soka_gakkai', 'japan').
country('atenism', 'ancient_egypt').
country('cult_of_reason', 'french_first_republic').
country('babylonian_religion', 'babylonia').
country('nichiren_sh_sh_', 'japan').
country('grapevine_cross', 'georgia').
country('matha', 'india').
country('punic_religion', 'ancient_carthage').
country('coconut_religion', 'vietnam').
country('makuya_church', 'japan').
country('donyi_polo', 'india').
country('mango_worship', 'people_s_republic_of_china').
country('midewiwin', 'united_states_of_america').
country('midewiwin', 'canada').
country('church_universal_and_triumphant', 'united_states_of_america').
country('universalist_church_of_america', 'united_states_of_america').
country('tensh__k_tai_jing_ky_', 'japan').
country('__o_m_u', 'vietnam').
country('mundial_church_of_god_s_power', 'brazil').
country('ugaritic_religion', 'ugarit').
country('igreja_crist__maranata', 'brazil').
country('apokpa_marup', 'india').
country('kid_', 'yamatai').
country('bell_church', 'philippines').
country('international_horse_procession_hakendover_tienen', 'belgium').
country('vianova', 'belgium').
country('knights_of_seth', 'united_kingdom').
country('laestadianism_in_america', 'united_states_of_america').
country('temple_of_the_true_inner_light', 'united_states_of_america').
country('temple_of_the_true_inner_light', '2').
country('zenith_applied_philosophy', 'new_zealand').
country('houkoukai', 'japan').
country('adat_musi', 'indonesia').
country('dunamis_international_gospel_centre', 'headquarters').
country('dunamis_international_gospel_centre', 'nigeria').
country('big_drum', 'canada').
country('big_drum', 'united_states_of_america').
country('traditional_choctaw_religion', 'united_states_of_america').
country('pilgrim_s_table_at_saint_julian_s_hospital', 'belgium').
country('st_anthony_s_day_celebrations_in_flanders', 'belgium').
country('om_lovers', 'united_states_of_america').
country('integral_humanism', 'india').
country('seish_k__faith', 'japan').
country('taishi_cult', 'japan').
part_of('zoroastrianism', 'iranian_religions').
part_of('rastafari', 'new_religious_movement').
part_of('unitarianism', 'liberal_christianity').
part_of('sumerian_religion', 'mesopotamia').
part_of('modern_asatru', 'modern_paganism').
part_of('soka_gakkai', 'shinsh_ky_').
part_of('canaanite_religion', 'ancient_semitic_religion').
part_of('anglo_catholicism', 'anglicanism').
part_of('babylonian_religion', 'sumerian_religion').
part_of('hellenistic_judaism', 'judaism').
part_of('ancient_mesopotamian_religion', 'sumerian_religion').
part_of('low_church', 'christianity').
part_of('second_temple_judaism', 'history_of_judaism').
part_of('traditional_berber_religion', 'culture').
part_of('aztec_religion', 'aztec_culture').
part_of('ryukyuan_religion', 'paganism').
part_of('etruscan_religion', 'etruscan_culture').
part_of('etruscan_religion', 'roman_mythology').
part_of('finnish_neopaganism', 'neopaganism_in_scandinavia').
part_of('hittite_religion', 'hittite_culture').
part_of('nabataean_religion', 'ancient_semitic_religion').
part_of('ugaritic_religion', 'culture').
part_of('beliefs_and_practices_of_the_church_of_jesus_christ_of_latter_day_saints', 'the_church_of_jesus_christ_of_latter_day_saints').
part_of('beliefs_and_practices_of_the_church_of_jesus_christ_of_latter_day_saints', 'latter_day_saint_movement').
part_of('arathi', 'christianity').
part_of('african_religion', 'religion_in_africa').
part_of('the_new_church', 'swedenborgian_church').
part_of('kingdom_movement', 'social_gospel').
part_of('uniformitarianism', 'science').
part_of('uniformitarianism', 'philosophy_of_science').
part_of('uniformitarianism', 'geology').
part_of('mind_body_dualism', 'ontology').
part_of('mind_body_dualism', 'philosophy_of_mind').
part_of('critical_rationalism', 'popperism').
part_of('epiphenomenalism', 'philosophy_of_mind').
part_of('transcendental_idealism', 'kantianism').
part_of('na_ve_realism', 'psychology_terminology').
part_of('compatibilism', 'compatibilism_and_incompatibilism').
part_of('neutral_monism', 'monism').
part_of('neutral_monism', 'philosophy_of_mind').
part_of('probabilism', 'philosophy').
part_of('interactionism', 'philosophy_of_mind').
part_of('property_dualism', 'philosophy_of_mind').
part_of('radical_behaviorism', 'psychology_terminology').
part_of('transcendental_analytic', 'q1534211').
part_of('aggressionism', 'philosophy_of_war').
part_of('neorationalism', 'rationalism').
part_of('hylemorphic_dualism', 'philosophy_of_mind').
part_of('astrolatry', 'religion').
official_language('zoroastrianism', 'avestan').
named_after('zoroastrianism', 'zoroaster').
named_after('jainism', 'arihant').
named_after('bah____faith', 'bah__u_ll_h').
named_after('rastafari', 'haile_selassie_i').
named_after('tengrism', 'tengri').
named_after('b_bism', 'b_b').
named_after('historical_vedic_religion', 'vedas').
named_after('arminianism', 'jacobus_arminius').
named_after('soka_gakkai', 'value_creation').
named_after('ariosophy', 'aryan').
named_after('aztec_religion', 'aztec').
named_after('nicene_christianity', 'first_council_of_nicaea').
named_after('ignatian_spirituality', 'ignatius_of_loyola').
named_after('the_new_church', 'emmanuel_swedenborg').
named_after('platonism', 'plato').
named_after('euhemerism', 'euhemerus').
named_after('contractualism', 'social_contract').
named_after('platonic_realism', 'plato').
named_after('occamism', 'william_of_ockham').
named_after('lockean_proviso', 'john_locke').
named_after('platonic_idealism', 'plato').
named_after('erastianism', 'thomas_erastus').
named_after('thought_of_thomas_aquinas', 'thomas_aquinas').
named_after('philosophical_thought_of_schopenhauer', 'arthur_schopenhauer').
named_after('uwaisi', 'uwais_qarni').
named_after('gion_faith', 'jetavana').
named_after('taishi_cult', 'prince_sh_toku').
significant_event('zoroastrianism', 'muslim_conquest_of_persia').
follows('jainism', 'historical_vedic_religion').
follows('jainism', 'hinduism').
follows('pluralism', 'dualism').
flag('jainism', 'jain_flag').
headquarters_location('scientology', 'los_angeles').
headquarters_location('soka_gakkai', 'shinanomachi').
headquarters_location('eckankar', 'chanhassen').
headquarters_location('nichiren_sh_sh_', 'taiseki_ji').
headquarters_location('universalist_church_of_america', 'united_states_of_america').
headquarters_location('tensh__k_tai_jing_ky_', 'tabuse').
headquarters_location('bell_church', 'la_trinidad').
headquarters_location('zenith_applied_philosophy', 'christchurch').
creator('scientology', 'l__ron_hubbard').
creator('thelema', 'aleister_crowley').
creator('pastafarianism', 'bobby_henderson').
creator('homaranismo', 'l__l__zamenhof').
creator('arar__religion', 'ewe').
creator('formalism', 'david_hilbert').
creator('modal_realism', 'david_lewis').
creator('integral_humanism', 'deendayal_upadhyaya').
creator('transcendental_analytic', 'immanuel_kant').
creator('legitimacy', 'edmund_husserl').
creator('voice_of_poetry', 'michael_oakeshott').
standards_body('scientology', 'religious_technology_center').
religion_or_worldview('catharism', 'christianity').
religion_or_worldview('catharism', 'dualism').
religion_or_worldview('rule_of_osha', 'if_').
religion_or_worldview('kemetism', 'modern_paganism').
religion_or_worldview('sallekhana', 'jainism').
religion_or_worldview('makuya_church', 'christianity').
religion_or_worldview('arab_muslims', 'islam').
religion_or_worldview('amazighs_christians_donatians', 'christianity').
religion_or_worldview('israelites_as_the_chosen_people', 'judaism').
religion_or_worldview('seish_k__faith', 'nichiren_buddhism').
religion_or_worldview('seish_k__faith', 'shinto').
conflict('catharism', 'albigensian_crusade').
based_on('modern_paganism', 'paganism').
based_on('punic_religion', 'canaanite_religion').
based_on('svetosavlje', 'eastern_orthodoxy').
has_part_s__of_the_class('modern_paganism', 'polytheistic_reconstructionism').
ethnic_group('tengrism', 'mongolic_peoples').
ethnic_group('tengrism', 'turkic_peoples').
ethnic_group('bori_religion', 'hausa_people').
ethnic_group('akan_religion', 'akan').
ethnic_group('mapuche_religion', 'mapuche').
ethnic_group('svetosavlje', 'serbs').
ethnic_group('hangui', 'pumi').
opposite_of('unitarianism', 'holy_trinity').
opposite_of('anglo_catholicism', 'puritans').
opposite_of('low_church', 'high_church').
opposite_of('monism', 'pluralism').
opposite_of('uniformitarianism', 'time_variation_of_fundamental_constants').
opposite_of('uniformitarianism', 'q1385609').
opposite_of('obscurantism', 'enlightenmentism').
opposite_of('pluralism', 'monism').
opposite_of('mind_body_dualism', 'na_ve_realism').
opposite_of('na_ve_realism', 'mind_body_dualism').
opposite_of('compatibilism', 'incompatibilism').
opposite_of('exceptionalism', 'universality').
opposite_of('antihumanism', 'humanism').
opposite_of('innate_goodness', 'innate_evilness').
opposite_of('innate_evilness', 'innate_goodness').
opposite_of('enlightenmentism', 'obscurantism').
opposite_of('afterlife', 'previous_life').
said_to_be_the_same_as('ancient_roman_religion', 'roman_mythology').
said_to_be_the_same_as('sumerian_religion', 'mesopotamian_mythology').
said_to_be_the_same_as('sanamahism', 'meiteism').
said_to_be_the_same_as('brahmoism', 'adi_dharm').
said_to_be_the_same_as('adi_dharm', 'brahmoism').
said_to_be_the_same_as('hittite_religion', 'hittite_mythology').
said_to_be_the_same_as('meiteism', 'sanamahism').
said_to_be_the_same_as('samnite_religion', 'sabine_religion').
said_to_be_the_same_as('hlai_folk_religion', 'hlai_people').
said_to_be_the_same_as('sabine_religion', 'samnite_religion').
said_to_be_the_same_as('transcendental_idealism', 'transcendentalism').
followed_by('historical_vedic_religion', 'buddhism').
followed_by('historical_vedic_religion', 'jainism').
followed_by('historical_vedic_religion', 'hinduism').
followed_by('cult_of_reason', 'cult_of_the_supreme_being').
followed_by('sarnaism', 'tribe').
followed_by('monism', 'dualism').
facet_of('historical_vedic_religion', 'vedic_period').
facet_of('hellenistic_judaism', 'second_temple_judaism').
facet_of('hellenistic_judaism', 'hellenization').
facet_of('second_temple_judaism', 'hellenistic_judaism').
facet_of('native_american_religions', 'indigenous_cultures_of_the_americas').
facet_of('judaism_s_view_on_muhammad', 'judaism').
facet_of('ignatian_spirituality', 'society_of_jesus').
facet_of('mun', 'lepcha_people').
facet_of('beliefs_and_practices_of_the_church_of_jesus_christ_of_latter_day_saints', 'mormonism').
facet_of('beliefs_and_practices_of_the_church_of_jesus_christ_of_latter_day_saints', 'the_church_of_jesus_christ_of_latter_day_saints').
facet_of('knights_of_seth', 'dualistic_cosmology').
facet_of('knights_of_seth', 'dualism').
facet_of('visigothic_arianism', 'arianism_in_hispania').
facet_of('religion_of_sakalava_people', 'sakalava_people').
facet_of('wesenmystik', 'marguerite_porete').
facet_of('wesenmystik', 'mechthild_of_magdeburg').
facet_of('wesenmystik', 'christian_mysticism_in_the_middle_ages').
facet_of('nominalism', 'problem_of_universals').
facet_of('sensationism', 'empiricism').
facet_of('sensationism', 'cyrenaics').
facet_of('euhemerism', 'mythology').
facet_of('eliminative_materialism', 'philosophy_of_mind').
facet_of('double_truth', 'aristotelianism').
facet_of('double_truth', 'christianity').
facet_of('double_truth', 'faith_and_rationality').
facet_of('cosmic_pluralism', 'extraterrestrial_life').
facet_of('perdurantism', 'metaphysics').
facet_of('turtles_all_the_way_down', 'infinite_regress').
facet_of('moderate_realism', 'problem_of_universals').
facet_of('innate_goodness', 'chinese_philosophy').
facet_of('new_materialism', 'contemporary_philosophy').
facet_of('mou_zongsan_s_moral_metaphysics', 'new_confucianism').
facet_of('enlightenmentism', 'progressivism').
facet_of('afterlife', 'reincarnation').
facet_of('afterlife', 'immortality').
facet_of('uwaisi', 'sufism').
facet_of('tenjin_faith', 'tenjin').
facet_of('seish_k__faith', 'kat__kiyomasa').
facet_of('taishi_cult', 'prince_sh_toku').
facet_of('gory__faith', 'gory_').
related_category('rule_of_osha', 'category_candombl_s').
in_opposition_to('brahmanism', 'anti_brahminism').
in_opposition_to('pastafarianism', 'intelligent_design').
diaspora('yazidism', 'sweden').
diaspora('yazidism', 'armenia').
diaspora('yazidism', 'france').
diaspora('yazidism', 'australia').
diaspora('yazidism', 'united_states_of_america').
diaspora('yazidism', 'belgium').
diaspora('yazidism', 'russia').
diaspora('yazidism', 'germany').
diaspora('yazidism', 'canada').
diaspora('yazidism', 'georgia').
inspired_by('modern_asatru', 'asatru').
inspired_by('terasem_movement', 'earthseed').
business_division('soka_gakkai', 'the_seikyo_press').
social_media_followers('soka_gakkai', '13008').
social_media_followers('soka_gakkai', '251000').
social_media_followers('soka_gakkai', '16945').
social_media_followers('soka_gakkai', '290000').
social_media_followers('soka_gakkai', '18424').
social_media_followers('soka_gakkai', '322000').
social_media_followers('soka_gakkai', '368000').
social_media_followers('eckankar', '19000').
social_media_followers('eckankar', '21800').
social_media_followers('eckankar', '4815').
social_media_followers('eckankar', '25900').
social_media_followers('eckankar', '30500').
social_media_followers('eckankar', '33600').
social_media_followers('nichiren_sh_sh_', '5000').
social_media_followers('mundial_church_of_god_s_power', '30822').
social_media_followers('mundial_church_of_god_s_power', '31388').
social_media_followers('mundial_church_of_god_s_power', '30682').
social_media_followers('c3woc', '1641').
has_subsidiary('soka_gakkai', 'soka_gakkai_international').
has_subsidiary('church_universal_and_triumphant', 'the_summit_lighthouse').
house_publication('soka_gakkai', 'daibyakurenge').
present_in_work('heathenry', 'prose_edda').
present_in_work('heathenry', 'poetic_edda').
culture('babylonian_religion', 'babylonia').
culture('midewiwin', 'first_nations').
culture('midewiwin', 'native_americans_in_the_united_states').
culture('religion_and_ritual_of_the_cucuteni_trypillian_culture', 'cucuteni_trypillia_culture').
culture('big_drum', 'dakota_people').
culture('big_drum', 'potawatomi').
culture('big_drum', 'ojibwe').
anthem('umbanda', 'hino_da_umbanda').
time_period('hellenistic_judaism', 'hellenistic_period').
time_period('second_temple_judaism', 'second_temple_period').
time_period('gottgl_ubig', 'nazi_germany').
time_period('mango_worship', 'cultural_revolution').
time_period('religion_and_ritual_of_the_cucuteni_trypillian_culture', 'neolithic').
has_cause('hellenistic_judaism', 'hellenization').
indigenous_to('australian_aboriginal_mythology', 'indigenous_australians').
indigenous_to('aztec_religion', 'aztec').
indigenous_to('santo_daime', 'brazil').
indigenous_to('ryukyuan_religion', 'ryukyu').
indigenous_to('native_american_religions', 'indigenous_peoples_of_the_americas').
indigenous_to('proto_indo_iranian_religion', 'indo_iranians').
indigenous_to('proto_indo_iranian_religion', 'aryan').
indigenous_to('tai_folk_religion', 'thai_people').
indigenous_to('tai_folk_religion', 'isan_people').
indigenous_to('tai_folk_religion', 'ahom_people').
indigenous_to('tai_folk_religion', 'lao_people').
indigenous_to('midewiwin', 'maritimes').
indigenous_to('midewiwin', 'new_england').
indigenous_to('midewiwin', 'great_lakes_region').
indigenous_to('aluk_todolo', 'toraja').
indigenous_to('aluk_todolo', 'south_sulawesi').
indigenous_to('native_american_religion_in_north_america', 'indigenous_peoples_of_north_america').
intangible_cultural_heritage_status('if_', 'representative_list_of_the_intangible_cultural_heritage_of_humanity').
intangible_cultural_heritage_status('if_', 'masterpieces_of_the_oral_and_intangible_heritage_of_humanity').
intangible_cultural_heritage_status('international_horse_procession_hakendover_tienen', 'inventaris_vlaanderen_van_het_immaterieel_cultureel_erfgoed').
intangible_cultural_heritage_status('aluk_todolo', 'national_inventory_of_intangible_cultural_heritage_of_indonesia').
intangible_cultural_heritage_status('pilgrim_s_table_at_saint_julian_s_hospital', 'inventaris_vlaanderen_van_het_immaterieel_cultureel_erfgoed').
intangible_cultural_heritage_status('st_anthony_s_day_celebrations_in_flanders', 'inventaris_vlaanderen_van_het_immaterieel_cultureel_erfgoed').
located_in_the_administrative_territorial_entity('nichiren_sh_sh_', 'fujinomiya').
located_in_the_administrative_territorial_entity('makuya_church', 'tokyo').
located_in_the_administrative_territorial_entity('donyi_polo', 'arunachal_pradesh').
located_in_the_administrative_territorial_entity('daijokyo', 'nagoya').
located_in_the_administrative_territorial_entity('temple_of_the_true_inner_light', 'new_york_city').
located_in_the_administrative_territorial_entity('houkoukai', 'chiryu').
located_in_the_administrative_territorial_entity('traditional_choctaw_religion', 'choctaw').
located_in_the_administrative_territorial_entity('traditional_choctaw_religion', 'mississippi').
located_in_the_administrative_territorial_entity('traditional_choctaw_religion', 'oklahoma').
separated_from('nichiren_sh_sh_', 'nichiren_sh_').
continent('traditional_berber_religion', 'africa').
continent('abwoi_religion', 'africa').
significant_person('palo_mayombe', 'adolfo_constanzo').
significant_person('sensationism', '_tienne_bonnot_de_condillac').
significant_person('new_materialism', 'karen_barad').
significant_person('new_materialism', 'donna_haraway').
significant_person('new_materialism', 'catherine_malabou').
significant_person('new_materialism', 'katerina_kolozova').
significant_person('new_materialism', 'rosi_braidotti').
significant_person('new_materialism', 'manuel_delanda').
significant_person('new_materialism', 'tim_ingold').
significant_person('new_materialism', 'arturo_escobar').
significant_person('new_materialism', 'levi_bryant').
significant_person('new_materialism', 'isabelle_stengers').
significant_person('uwaisi', 'q5953017').
replaced_by('universalist_church_of_america', 'unitarian_universalist_association').
location_of_creation('arar__religion', 'dahomey').
day_in_year_for_periodic_occurrence('international_horse_procession_hakendover_tienen', 'easter_monday').
day_in_year_for_periodic_occurrence('pilgrim_s_table_at_saint_julian_s_hospital', 'maundy_thursday').
day_in_year_for_periodic_occurrence('st_anthony_s_day_celebrations_in_flanders', 'january_17').
month_of_the_year('international_horse_procession_hakendover_tienen', 'march').
month_of_the_year('international_horse_procession_hakendover_tienen', 'april').
month_of_the_year('pilgrim_s_table_at_saint_julian_s_hospital', 'march').
month_of_the_year('pilgrim_s_table_at_saint_julian_s_hospital', 'april').
month_of_the_year('st_anthony_s_day_celebrations_in_flanders', 'january').
event_interval('international_horse_procession_hakendover_tienen', '1').
event_interval('pilgrim_s_table_at_saint_julian_s_hospital', '1').
event_interval('st_anthony_s_day_celebrations_in_flanders', '1').
duration('international_horse_procession_hakendover_tienen', '1').
duration('pilgrim_s_table_at_saint_julian_s_hospital', '1').
duration('st_anthony_s_day_celebrations_in_flanders', '1').
day_of_week('international_horse_procession_hakendover_tienen', 'monday').
day_of_week('pilgrim_s_table_at_saint_julian_s_hospital', 'thursday').
archives_at('vianova', 'kadoc__documentatie__en_onderzoekscentrum_voor_religie__cultuur_en_samenleving').
archives_at('psychedelic_venus_church', 'bancroft_library').
main_subject('vianova', 'lifestance_organisation').
main_subject('horak_controversy', 'human_nature').
main_subject('predicativism', 'impredicativity').
main_subject('historical_cycles', 'philosophy_of_history').
legal_form('vianova', 'non_profit_organisation').
legal_form('c3woc', 'conglomerate').
movement('zenith_applied_philosophy', 'anti_communism').
field_of_work('zenith_applied_philosophy', 'personality_test').
field_of_work('psychedelic_venus_church', 'entheogen').
field_of_work('psychedelic_venus_church', 'orgy').
field_of_work('psychedelic_venus_church', 'cannabis_and_religion').
political_ideology('zenith_applied_philosophy', 'opposition_to_trade_unions').
total_revenue('c3woc', '42000').
worshipped_by('umbandism', 'nontheism').
worshipped_by('el_cantare', 'happy_science').
uses('hangui', 'priest').
published_in('muhammad_s_a_w_from_hira_cave_to_makkah', 'malaysia').
published_in('right_to_the_city', 'le_droit___la_ville').
publisher('muhammad_s_a_w_from_hira_cave_to_makkah', 'macmillan_publishers').
named_by('sensationism', 'joseph_marie__baron_de_g_rando').
item_disputed_by('mind_body_dualism', 'alfred_north_whitehead').
edition_or_translation_of('hylomorphism', 'mart_n_fierro').
discoverer_or_inventor('logical_atomism', 'bertrand_russell').
discoverer_or_inventor('radical_behaviorism', 'b__f__skinner').
discoverer_or_inventor('marx_s_theory_of_human_nature', 'karl_marx').
discoverer_or_inventor('bundle_theory', 'david_hume').
discoverer_or_inventor('agential_realism', 'karen_barad').
discoverer_or_inventor('thought_of_thomas_aquinas', 'thomas_aquinas').
discoverer_or_inventor('philosophical_thought_of_schopenhauer', 'arthur_schopenhauer').
discoverer_or_inventor('pantheistic_monism', 'giordano_bruno').
discoverer_or_inventor('humean_definition_of_causality', 'david_hume').
discoverer_or_inventor('mou_zongsan_s_moral_metaphysics', 'mou_zongsan').
author('right_to_the_city', 'henri_lefebvre').
depicts('turtles_all_the_way_down', 'world_turtle').
endorsed_by('innate_goodness', 'mencius').
endorsed_by('innate_goodness', 'zhu_xi').
endorsed_by('innate_evilness', 'xunzi').
theorised_by('legitimacy', 'edmund_husserl').
including('afterlife', 'tartarus').
including('afterlife', 'underworld').
including('afterlife', 'greek_underworld').
including('afterlife', 'heaven').
including('afterlife', 'elysium').
including('afterlife', 'valhalla').
including('afterlife', 'niflheim').
including('afterlife', 'sheol').
